version: "3.8"
services:
  mongodb:
    container_name: maplelegends_vote_reminder-mongodb
    volumes:
      - /mnt/gluster/docker/maplelegends_vote_reminder-mongodb:/data/db
    networks:
      - maplelegends_vote_reminder
    expose:
      - 27017
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true

  proxy:
    container_name: maplelegends_vote_reminder-proxy_server
    image: ghcr.io/gordonpn/maplelegends_vote_reminder-proxy_server:stable
    environment:
      - APP_ENV=production
      - FLASK_ENV=production
    networks:
      - maplelegends_vote_reminder
      - traefik-public
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
    # healthcheck:
    #   test: curl --fail -s http://localhost:8000/health || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.maplelegends_vote_reminder.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik-public"

  bot:
    container_name: maplelegends_vote_reminder-discord_bot
    image: ghcr.io/gordonpn/maplelegends_vote_reminder-discord_bot:stable
    networks:
      - maplelegends_vote_reminder
    environment:
      - APP_ENV=production
      - DOMAIN=https://maplelegends.gordon-pn.com
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s

networks:
  maplelegends_vote_reminder:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
