version: "3.8"
services:
  mongodb:
    container_name: maplelegends_vote_reminder-mongodb
    user: "1001:1001"
    volumes:
      - /mnt/share/docker/maplelegends_vote_reminder/mongodb:/data
      - /mnt/share/docker/maplelegends_vote_reminder/workspace/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - maplelegends_vote_reminder
    expose:
      - 27017
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
          - node.labels.name != dev

  proxy:
    container_name: maplelegends_vote_reminder-proxy_server
    image: ghcr.io/gordonpn/maplelegends_vote_reminder-proxy-server:stable
    environment:
      - APP_ENV=production
      - FLASK_ENV=production
    networks:
      - maplelegends_vote_reminder
    expose:
      - 5000
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/health || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s


  bot:
    container_name: maplelegends_vote_reminder-discord_bot
    image: ghcr.io/gordonpn/maplelegends_vote_reminder-discord-bot:stable
    networks:
      - maplelegends_vote_reminder
    environment:
      - APP_ENV=production
      - DOMAIN=https://maplelegends.gordon-pn.com
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s

  nginx:
    container_name: maplelegends_vote_reminder-nginx
    image: ghcr.io/gordonpn/maplelegends_vote_reminder-nginx:stable
    networks:
      - traefik-public
      - maplelegends_vote_reminder
    expose:
      - 80
    labels:
      - "traefik.enable=true"
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.maplelegends_vote_reminder.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.maplelegends_vote_reminder.entrypoints=websecure"
        - "traefik.http.routers.maplelegends_vote_reminder.middlewares=secured_headers@file"
        - "traefik.http.routers.maplelegends_vote_reminder.service=maplelegends_vote_reminder@docker"
        - "traefik.http.routers.maplelegends_vote_reminder.tls=true"
        - "traefik.http.routers.maplelegends_vote_reminder.tls.certresolver=leresolver"
        - "traefik.http.routers.maplelegends_vote_reminder.rule=Host(`maplelegends.gordon-pn.com`)"

networks:
  maplelegends_vote_reminder:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
